### ISSUE TITLE
[TODO] remedy `Hard` misuse

### ISSUE THREAD

**Issue by L-M-Sherlock** [open-spaced-repetition/fsrs4anki-helper#454]
- [ ] add a feature to replace `hard` with `again` of revlog
- [ ] allow user to set the date range of misuse
- [ ] store remedy logs to make this feature undoable
